nama = input("nama : ")
print (nama)
nim = input("nim : ")
var1 = int(nim)
print (nim)
ttl = input("ttl : ")
print = (ttl)
umur = input("umur : ")
var2 = int(umur)
print = (umur)
jk = input("jk : ")
print = (jk)
jurusan = input("jurusan : ")
print = (jurusan)
alamat = input("alamat : ")
print = (alamat)